"""
Django settings for hoop_and_go project.


Generated by 'django-admin startproject' using Django 6.0.6.


For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/


For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""



#   Edited by:
#   Ionut Ciobanu
#   Michal Pokojny //13/07/26



from pathlib import Path
import os
from decouple import config  # python-decouple is used to manage environment variables and settings
import dj_database_url  # configure database using a single URL, for deploying to platforms.
from django.contrib.messages import constants as messages  # used to customize the message tags used in Django messaging framework.



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-secret')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
# SECURITY WARNING: don't run with debug turned on in production!


# Determine if the application is in development mode
development = config('DEV_MODE', default=True, cast=bool)


# Use a local secret key fallback in development.
# In production, SECRET_KEY must be set by the deployment platform.
if development:
    SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-secret')
else:
    SECRET_KEY = config('SECRET_KEY')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


# security settings for production
DEBUG = development


# Email settings
# In development, use the console backend so email actions do not require a running SMTP server.
if development:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'webmaster@localhost'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='localhost')
    EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='webmaster@localhost')


X_FRAME_OPTIONS = 'SAMEORIGIN'


# Allow all hosts in development, restrict to specific host in production
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://127.0.0.1']
CSRF_COOKIE_DOMAIN = None

HOSTNAME = config('HOSTNAME', default='')
if HOSTNAME:
    ALLOWED_HOSTS.append(HOSTNAME)
    CSRF_TRUSTED_ORIGINS.extend([f'http://{HOSTNAME}', f'https://{HOSTNAME}'])
    if not development:
        CSRF_COOKIE_DOMAIN = HOSTNAME


# Production proxy / cookie settings
if not development:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth social authentication
    'django_summernote',  # Rich text editor for admin
    'allauth',  # authentication and login/logout system
    'allauth.account',  # account management
    'allauth.socialaccount',  # social account integration
    'crispy_forms',  # for better form rendering
    'crispy_forms.bootstrap',  # for Bootstrap form rendering
    'home',
    'manage_events',
    'view_accounts',
    'vehicle_registration',
]


ACCOUNT_FORMS = {
    "login": "forms.CustomLoginForm",
}



SITE_ID = 1


# Redirect URLs after login/logout/signup
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/'


MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


ACCOUNT_EMAIL_VERIFICATION = 'none'


# AllAuth Configuration
# https://django-allauth.readthedocs.io/en/latest/
ACCOUNT_LOGIN_METHODS = {'email', 'username'}  # Allow login with username or email
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_SESSION_REMEMBER = True  # Remember user for 1 week
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'


# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
]


ROOT_URLCONF = 'hoop_and_go.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'allauth'),  # Include allauth templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = [
    # Default Django authentication
    'django.contrib.auth.backends.ModelBackend',


    # allauth authentication
    'allauth.account.auth_backends.AuthenticationBackend',
]



WSGI_APPLICATION = 'hoop_and_go.wsgi.application'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


#   Use PostgreSQL/Neon in both development and production
DATABASE_URL = config('DATABASE_URL', default=None)
if not DATABASE_URL:
    raise ValueError("DATABASE_URL Unknown!")

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'UTC'


USE_I18N = True


USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Use WhiteNoise for production static file serving.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'