# Generated by Django 6.0.6 on 2026-08-05 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_type',
            field=models.CharField(default='Basketball', max_length=50),
        ),
    ]
